### ISSUE TITLE
Number of data points function issue

### ISSUE THREAD

**Issue by Jupuu** [alsc2164/Scheele_CSCI2270_FinalProject#3]
The function of  Number of data points has an issue. If the user calls this function for the first time he or she will get and answer that  "The number of data points: 30". Then call the function again The output will be "The number of data points: 60" but the user will expect it  to be 30. If the User calls the function again  the user gets 90 data points. I think that the problem here is that every time you call this function, instead of getting the a new number for the data points, it adds the old number you counted last time to the new number so that's why you get 60 data points.

**Comment by CodyConstine** [comment]
Thank you for reporting a actual bug. I fixed this issue.
